# detekt.yml
# This file defines the configuration for Detekt.

detekt:
  config:
    # List of paths to additional config files to be imported.
    # Useful for extending configurations or separating them per project module.
    includes: []

    # Path patterns to exclude from analysis (e.g., test files).
    excludes: []

  build:
    # Determines if detekt should fail the build if there are any findings.
    failFast: false

  output:
    # Configure output paths for reports in various formats.
    reports:
      xml:
        enabled: true
        destination: "build/reports/detekt/detekt-report.xml"
      html:
        enabled: true
        destination: "build/reports/detekt/detekt-report.html"
      txt:
        enabled: false
      sarif:
        enabled: false
      custom:
        enabled: false
        destination: "path/to/custom-report"
        # Template file for the custom report.
        #template: "path/to/template-file"

  processors:
    # Additional code processors
    active: true
    excludeAnnotatedClasses:
      - kotlinx.serialization.Serializable

  plugins:
    # Specify plugins for additional checks.
    active: true

  rules:
    # Activate/deactivate specific rules or rule sets.
    active: true
    complexity:
      active: true
      LargeClass:
        active: true
        threshold: 150
    formatting:
      active: true
      Indentation:
        active: true
    style:
      active: true
      WildcardImport:
        active: false

  sonar:
    enabled: true
    xmlReportPath: "build/reports/detekt/detekt-report.xml"
    # Base path that will be stripped from file paths in the XML report.
    basePath: "./"
