name: Android CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  checks: write
  actions: read
  contents: read
  security-events: write
  pull-requests: write

jobs:
  Build-And-Test:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Enable KVM
      run: |
          echo 'KERNEL=="kvm", GROUP="kvm", MODE="0666", OPTIONS+="static_node=kvm"' | sudo tee /etc/udev/rules.d/99-kvm4all.rules
          sudo udevadm control --reload-rules
          sudo udevadm trigger --name-match=kvm

    - name: set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'adopt'
        cache: gradle

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew

    - name: Run lint
      run: ./gradlew lint

    - name: Run detekt
      run: ./gradlew detekt
    
    - name: Upload SARIF to GitHub using the upload-sarif action
      uses: github/codeql-action/upload-sarif@v3
      if: success() || failure()
      with:
        sarif_file: app/build/reports/detekt/detekt.sarif
      
    - name: Run connected tests
      uses: ReactiveCircus/android-emulator-runner@v2
      with:
        api-level: 30
        target: google_apis
        arch: x86_64
        script: ./gradlew connectedCheck

    - name: Check reports
      run: |
        REPORT_PATH=$(find app/build/outputs/androidTest-results/ -type f -name "*.xml")
        echo "REPORT_PATH=$REPORT_PATH" >> $GITHUB_ENV  
    
    - name: Test Report
      uses: dorny/test-reporter@v1
      if: success() || failure()
      with:
        name: Android UI Tests            # Name of the check run which will be created
        path: ${{env.REPORT_PATH}}    # Path to test results
        reporter: java-junit
